--Highly divisible triangular number
--Problem 12
--The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

--1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

--Let us list the factors of the first seven triangle numbers:

 --1: 1
 --3: 1,3
 --6: 1,2,3,6
--10: 1,2,5,10
--15: 1,3,5,15
--21: 1,3,7,21
--28: 1,2,4,7,14,28
--We can see that 28 is the first triangle number to have over five divisors.

--What is the value of the first triangle number to have over five hundred divisors?

import Data.List

{-factor :: Int -> [Int]-}
{-factor n = filter (\x -> n `mod` x == 0) [1 .. n]-}

primes :: Int -> [Int]
primes 1 = [1]
primes n = let Just m = find (\x -> mod n x == 0) [2 .. n] in m : primes (n `div` m)

leng = product . map ((+1) . length) . group . init . primes

a n = n * (n+1) `div` 2

main = do
    print $ find (\(_, x) -> x > 500) $ map (\x -> (a x, leng $ a x)) [1 .. ] 
